apiVersion: v1
kind: Service
metadata:
  name: escrow
  namespace: fundabiz
  labels:
    app: escrow
spec:
  type: ClusterIP
  selector:
    app: escrow
  ports:
    - port: 4003
      targetPort: 4003
      protocol: TCP
      name: http
