apiVersion: v1
kind: Service
metadata:
  name: mpesa
  namespace: fundabiz
  labels:
    app: mpesa
spec:
  type: ClusterIP
  selector:
    app: mpesa
  ports:
    - port: 4005
      targetPort: 4005
      protocol: TCP
      name: http
