apiVersion: v1
kind: Service
metadata:
  name: wallet
  namespace: fundabiz
  labels:
    app: wallet
spec:
  type: ClusterIP
  selector:
    app: wallet
  ports:
    - port: 4004
      targetPort: 4004
      protocol: TCP
      name: http
